### ISSUE TITLE
Visualization scheme for gene maps

### ISSUE THREAD

**Issue by angadps** [ludvb/xfuse#41]
Hello,

This is mostly a question to better understand the current visualizations and if and how they could be configured. Hope this hasn't been already discussed.

I've run xfuse on a couple of dozen samples so far and I'm trying to investigate about a dozen genes in each of the samples. Based on the raw Visium gene expression data some of the plots aren't making sense to me. For instance, one of the genes is expressed in < 10 spots in the Visium data, still I see bright spots throughout the tissue in the gene maps analysis. Maybe having a better understanding of the visuals might help.

1) Is the data being normalized by default when visualizing the "xfused" gene expression? If so, the relative scaling can cause some of the regions to "light up", even though the absolute predicted expression values might be low. This would not require a scale/legend as there isn't one right now. However, if the visualization is that of the absolute values, having a scale would be useful.

2) Is the visualization happening on the the original scale, or on a log-scale? Some of the genes are both highly expressed throughout the tissue and have large variation in the expression levels. Visualizing using a log scale can help catch the high expression values throughout along with capturing the differences.

Alternatively, are there configurable options for the above which I can use to display my plots?

Thanks,
--Angad.

**Comment by ludvb** [comment]
Hi Angad,

The gene maps use original scale data. By default, the data for each gene is normalized to the range of the colormap. There is no pixel-wise normalization. I agree that a scale would be very useful.

The data that is shown is the estimated posterior mean and not the observed expression. In case of low-expressed genes, the posterior mean will likely be much smaller than 1 and should not be taken to imply actual expression. It is also likely that the prediction has a high degree of uncertainty, as there may be insufficient data to reliably estimate expression levels.

Here are all the config options for the gene maps analysis with brief comments:

```toml
[analyses.analysis-gene_maps.options]
gene_regex = ".*"     # Regex specifying which genes to predict
num_samples = 10      # Number of Monte Carlo samples to draw from the inferred posterior
genes_per_batch = 10  # Number of genes per batch (use a lower value if you get OOM errors)
predict_mean = true   # Whether to draw samples of the posterior mean or the emitted negative binomial count values
normalize = false     # Whether to use pixel-wise normalization
mask_tissue = true    # Whether to mask out regions outside the tissue
scale = 1.0           # A rescaling factor in the range (0, 1). A lower value speeds up the analysis and results in smaller output files (at the cost of lower resolution).
writer = "image"      # Output format (can be either "image" or "tensor")
```

I think a good idea may be to set the `writer` argument to "tensor". This will save the expression maps as torch tensors, which can be loaded in Python using `torch.load`. The tensors will have the shape (num_samples, height, width) and contain the unnormalized samples. It would then be possible to normalize the data in the way most suitable for your analysis and to get a better sense of predictive dispersion/uncertainty.

Let me know if you have any questions!
